"""Optional LLM judge over notification output (requires Ollama when exercised)."""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from agents.notification_agent import notification_agent  # noqa: E402


def judge_notification_output(result: dict) -> str:
    """Evaluates the notification agent's output using Ollama."""
    import ollama

    notification = result.get("notification", {})
    prompt = f"""
    Evaluate the following notification output generated by the Notification Agent.
    It should contain a 'status', 'channel', 'message', and 'error'.
    The message must NOT contain unnecessary personal data and should clearly confirm the appointment.

    Notification Data: {notification}

    Respond strictly with "VALID" or "INVALID".
    """
    model = os.environ.get("OLLAMA_MODEL", "llama3.2:3b").strip() or "llama3.2:3b"
    try:
        response = ollama.chat(
            model=model,
            messages=[
                {
                    "role": "system",
                    "content": "You are a strict evaluator. Evaluate agent outputs. Return ONLY 'VALID' or 'INVALID'.",
                },
                {"role": "user", "content": prompt},
            ],
        )
        return response["message"]["content"].strip().upper()
    except Exception as e:  # noqa: BLE001
        print(f"\n[Judge Warning] Ollama judge unavailable: {e}")
        return "UNABLE_TO_JUDGE (OLLAMA OFFLINE)"


@pytest.mark.skipif(
    os.environ.get("SKIP_NOTIFICATION_JUDGE", "").strip().lower() in ("1", "true", "yes"),
    reason="SKIP_NOTIFICATION_JUDGE=1",
)
def test_notification_llm_judge() -> None:
    from unittest.mock import patch

    fake_agent = {"message": {"content": '{"message": "Your appointment is confirmed."}'}}
    fake_judge = {"message": {"content": "VALID"}}
    state = {
        "appointment": {
            "appointment_id": "A123",
            "user_name": "Alice",
            "user_contact": "+123456789",
            "doctor": "Smith",
            "specialization": "Dentistry",
            "time_iso": "2026-05-03T10:00:00",
            "channel": "sms",
        },
        "status": "complete",
        "errors": [],
    }

    with patch("ollama.chat", side_effect=[fake_agent, fake_judge]), patch(
        "agents.notification_agent.save_appointment",
        return_value=True,
    ):
        result = notification_agent(state)
        evaluation = judge_notification_output(result)

    assert evaluation == "VALID"
