import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.notification_agent import notification_agent
import ollama

def judge_notification_output(result: dict) -> str:
    """Uses LLM-as-a-judge to evaluate the notification agent's output."""
    notification = result.get("notification", {})
    
    prompt = f"""
    Evaluate the following notification output generated by the Notification Agent.
    It should contain a 'status', 'channel', 'message', and 'error'.
    The message must NOT contain unnecessary personal data and should clearly confirm the appointment.
    
    Notification Data: {notification}
    
    Respond strictly with "VALID" or "INVALID".
    """
    
    try:
        response = ollama.chat(
            model="llama3.2:3b",
            messages=[
                {"role": "system", "content": "You are a strict LLM-as-a-Judge. Evaluate agent outputs. Return ONLY 'VALID' or 'INVALID'."},
                {"role": "user", "content": prompt}
            ]
        )
        return response['message']['content'].strip().upper()
    except Exception as e:
        print(f"\n[Judge Warning] Could not connect to Ollama to evaluate the output. Please ensure Ollama is running. Error: {e}")
        return "UNABLE_TO_JUDGE (OLLAMA OFFLINE)"

def test_notification_llm_judge():
    state = {
        "appointment": {
            "appointment_id": "A123",
            "user_name": "Alice",
            "user_contact": "+123456789",
            "doctor": "Smith",
            "specialization": "Dentist",
            "time_iso": "2026-05-03T10:00:00",
            "channel": "sms"
        }
    }

    result = notification_agent(state)
    evaluation = judge_notification_output(result)

    print("Agent Output:", result)
    print("Judge Result:", evaluation)

    assert evaluation in ["VALID", "INVALID", "UNABLE_TO_JUDGE (OLLAMA OFFLINE)"]

if __name__ == "__main__":
    test_notification_llm_judge()
